USE [master]
GO
/****** Object:  Database [Usuarios]    Script Date: 26/08/2023 10:59:37 p. m. ******/
CREATE DATABASE [Usuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'proyecto_cons', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\proyecto_cons.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'proyecto_cons_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\proyecto_cons_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Usuarios] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Usuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Usuarios] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Usuarios] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Usuarios] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Usuarios] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Usuarios] SET ARITHABORT OFF 
GO
ALTER DATABASE [Usuarios] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Usuarios] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Usuarios] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Usuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Usuarios] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Usuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Usuarios] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Usuarios] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Usuarios] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Usuarios] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Usuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Usuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Usuarios] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Usuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Usuarios] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Usuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Usuarios] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Usuarios] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Usuarios] SET  MULTI_USER 
GO
ALTER DATABASE [Usuarios] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Usuarios] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Usuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Usuarios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Usuarios] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Usuarios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Usuarios] SET QUERY_STORE = ON
GO
ALTER DATABASE [Usuarios] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Usuarios]
GO
/****** Object:  Table [dbo].[Useers]    Script Date: 26/08/2023 10:59:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Useers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Contrasena] [varchar](20) NOT NULL,
	[Rol] [int] NOT NULL,
	[Puntuacion] [int] NULL,
 CONSTRAINT [PK_Useers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Useers] ON 
GO
INSERT [dbo].[Useers] ([Id], [Nombre], [Contrasena], [Rol], [Puntuacion]) VALUES (2, N'omarsinho', N'omar123', 1, 0)
GO
INSERT [dbo].[Useers] ([Id], [Nombre], [Contrasena], [Rol], [Puntuacion]) VALUES (3, N'Admin', N'1234', 1, 0)
GO
INSERT [dbo].[Useers] ([Id], [Nombre], [Contrasena], [Rol], [Puntuacion]) VALUES (1004, N'omar', N'123', 2, 0)
GO
SET IDENTITY_INSERT [dbo].[Useers] OFF
GO
USE [master]
GO
ALTER DATABASE [Usuarios] SET  READ_WRITE 
GO
